services:
  valkey:
    image: valkey/valkey:8-alpine
    ports:
      - 6379:6379
    networks:
      - broker_network

  pushnotifications:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - valkey
    networks:
      - broker_network
    ports:
      - 3002:3002
    environment:
      VALKEY_HOST: valkey
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}
      SOCKET_CONNECTION: tcp://stream_analysis:5556
